# ==============================================================================
# Runtime Stage Only
# ==============================================================================
FROM ubuntu:24.04

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install Runtime Dependencies
# These must match the libraries your binary was linked against.
# Note: We REMOVED the user creation steps because 'ubuntu' (UID 1000) exists by default.
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libcurl4 \
    libssl3 \
    libuuid1 \
    libjson-c5 \
    liboath0t64 \
    unixodbc \
    tdsodbc \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Create the uploads directory for BLOB_PATH
# We use the existing 'ubuntu' user (UID 1000)
RUN mkdir -p /app/uploads && chown ubuntu:ubuntu /app/uploads

# --- COPY THE BINARY ---
# This copies the 'apiserver' generated by the GitHub Action into the image
COPY --chown=ubuntu:ubuntu apiserver /app/apiserver

# Ensure it is executable
RUN chmod +x /app/apiserver

# Define the mount point for Kubernetes PVCs
VOLUME ["/app/uploads"]

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# 1. Non-Sensitive Defaults
ENV PORT=8080
ENV POOL_SIZE=24
ENV IO_THREADS=4
ENV QUEUE_CAPACITY=500
ENV CORS_ORIGINS="null,file://"
ENV BLOB_PATH="/app/uploads"
ENV JWT_TIMEOUT_SECONDS=300
ENV REMOTE_API_URL="http://localhost:8080"

# 2. Security Sensitive Variables (Empty for injection via K8s Secrets)
ENV DB1=""
ENV LOGINDB=""
ENV JWT_SECRET=""
ENV API_KEY=""
ENV REMOTE_API_USER=""
ENV REMOTE_API_PASS=""

# Expose port
EXPOSE 8080

# Switch to the existing non-root user 'ubuntu' (UID 1000)
USER ubuntu

# Start the server
CMD ["./apiserver"]