sonar.projectKey=cppservergit_apiserver2
sonar.organization=cppservergit
sonar.host.url=https://sonarcloud.io

# Source and standard
sonar.sources=src
sonar.cfamily.compile-commands=bw-output/compile_commands.json
sonar.lang.opt.cpp.std=c++23

# Exclusions
sonar.coverage.exclusions=**/*.cpp, **/*.hpp, **/*.c, **/*.h
sonar.exclusions=obj/**, apiserver*, **/*.sh, **/*.yaml, **/*.md, **/*.txt