# ==============================================================================
# 1. SECRETS
# Sensitive data from run.sh
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: apiserver-secrets
type: Opaque
stringData:
  # Database Connection Strings
  DB1: "Driver=FreeTDS;SERVER=demodb.mshome.net;PORT=1433;DATABASE=demodb;UID=sa;PWD=Basica2024;APP=apiserver;Encryption=off;ClientCharset=UTF-8"
  LOGINDB: "Driver=FreeTDS;SERVER=demodb.mshome.net;PORT=1433;DATABASE=testdb;UID=sa;PWD=Basica2024;APP=apiserver-login;Encryption=off;ClientCharset=UTF-8"
  
  # Security Keys
  JWT_SECRET: "B@asica2025*uuid0998554j93m722pQ"
  API_KEY: "6976f434-d9c1-11f0-93b8-5254000f64af"
  
  # Remote API Credentials
  REMOTE_API_USER: "mcordova"
  REMOTE_API_PASS: "basica"

---
# ==============================================================================
# 2. STORAGE (PVC)
# Abstract storage claim - decoupling from host paths
# ==============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apiserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # The storage class will default to the cluster's default (e.g., microk8s-hostpath)
  # storageClassName: microk8s-hostpath

---
# ==============================================================================
# 3. DEPLOYMENT
# The application pods
# ==============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-deployment
  labels:
    app: apiserver2
spec:
  # Initial replicas. HPA will adjust this number (2 to 4) automatically.
  replicas: 2
  selector:
    matchLabels:
      app: apiserver2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: apiserver2
    spec:
      # --- SECURITY CONTEXT ---
      # Forces the pod to run as UID 1000.
      # fsGroup: 1000 is CRITICAL here: it tells K8s to change the ownership
      # of the mounted PVC volume to group 1000 so the pod can write to it.
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
      - name: apiserver2
        image: cppserver/apiserver2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
        # --- Environment Variables ---
        env:
        # Non-sensitive configs from run.sh
        - name: PORT
          value: "8080"
        - name: IO_THREADS
          value: "4"         # Aligned with CPU limit (4 cores)
        - name: POOL_SIZE
          value: "24"        # Matches your run.sh
        - name: QUEUE_CAPACITY
          value: "500"
        - name: CORS_ORIGINS
          value: "null,file://"
        - name: BLOB_PATH
          value: "/app/uploads" # Internal container path
        - name: JWT_TIMEOUT_SECONDS
          value: "300"
        - name: REMOTE_API_URL
          value: "http://localhost:8080"
          
        # Secrets injection
        - name: DB1
          valueFrom:
            secretKeyRef:
              name: apiserver-secrets
              key: DB1
        - name: LOGINDB
          valueFrom:
            secretKeyRef:
              name: apiserver-secrets
              key: LOGINDB
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: apiserver-secrets
              key: JWT_SECRET
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: apiserver-secrets
              key: API_KEY
        - name: REMOTE_API_USER
          valueFrom:
            secretKeyRef:
              name: apiserver-secrets
              key: REMOTE_API_USER
        - name: REMOTE_API_PASS
          valueFrom:
            secretKeyRef:
              name: apiserver-secrets
              key: REMOTE_API_PASS

        # --- Resources (Vertical Scaling) ---
        resources:
          requests:
            cpu: "1000m"   # Guarantee 1 CPU
            memory: "512Mi"
          limits:
            cpu: "4000m"   # Burst up to 4 CPUs (Matching IO_THREADS=4)
            memory: "1Gi"

        # --- Health Checks ---
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5

        # --- Volume Mounts ---
        volumeMounts:
        - name: blob-storage
          mountPath: /app/uploads

      volumes:
      - name: blob-storage
        persistentVolumeClaim:
          claimName: apiserver-pvc

---
# ==============================================================================
# 4. SERVICE
# Internal Load Balancer
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
spec:
  selector:
    app: apiserver2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  
  # BEST PRACTICE: 'ClusterIP' keeps the service internal.
  # Traffic MUST go through the Ingress Controller (Host Port 80/443).
  type: ClusterIP

---
# ==============================================================================
# 5. INGRESS
# External Access & Rules
# ==============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apiserver-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"

spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - path: /api/(.+)
        pathType: ImplementationSpecific
        backend:
          service:
            name: apiserver-service
            port:
              number: 8080

---
# ==============================================================================
# 6. HORIZONTAL POD AUTOSCALER (HPA)
# Dynamic Scaling (2 to 4 pods)
# ==============================================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apiserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apiserver-deployment
  
  minReplicas: 2
  maxReplicas: 4
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75