#pragma once

#include <string_view>
#include <array>
#include <stdexcept>
#include <sodium.h>
#include <algorithm>
#include <iostream>
#include <cstdlib>

// RAII class to guarantee libsodium is initialized automatically before main() executes
class SodiumInitializer {
public:
    SodiumInitializer() {
        if (sodium_init() < 0) {
            std::cerr << "CRITICAL FATAL: Failed to initialize libsodium. Aborting.\n";
            std::abort();
        }
    }
    
    // Prevent copying or moving this guard instance
    SodiumInitializer(const SodiumInitializer&) = delete;
    SodiumInitializer& operator=(const SodiumInitializer&) = delete;
};

// Global instance triggers initialization safely before any program logic runs
inline const SodiumInitializer g_sodium_guard;

namespace Crypto {
    // Compile-time fixed-size container for the Argon2id hash string
    using HashArray = std::array<char, crypto_pwhash_STRBYTES>;

    class PasswordHashingError : public std::runtime_error {
    public:
        using std::runtime_error::runtime_error;
    };

    class PasswordHashParseError : public std::runtime_error {
    public:
        using std::runtime_error::runtime_error;
    };

    /**
     * @brief Hashes a plaintext password using Argon2id.
     * 
     * @note The caller is responsible for clearing the plaintext password from 
     * memory (e.g., using sodium_memzero) after calling this function.
     */
    [[nodiscard]] inline HashArray hash_password(std::string_view password) {
        HashArray hash_buffer{}; // Zero-initialize the stack array

        // Uses the INTERACTIVE profile (approx. 64MB RAM, ~100ms calculation speed)
        if (const int result = crypto_pwhash_str(
                hash_buffer.data(),
                password.data(),
                password.length(),
                crypto_pwhash_OPSLIMIT_INTERACTIVE,
                crypto_pwhash_MEMLIMIT_INTERACTIVE
            ); result != 0) {
            throw PasswordHashingError("Password hashing failed: system out of memory.");
        }

        return hash_buffer;
    }

    /**
     * @brief Verifies a plaintext password against an Argon2id hash.
     * 
     * @note The caller is responsible for clearing the plaintext password from 
     * memory (e.g., using sodium_memzero) after verification.
     */
    [[nodiscard]] inline bool verify_password(std::string_view password, const HashArray& stored_hash) noexcept {
        const int result = crypto_pwhash_str_verify(
            stored_hash.data(),
            password.data(),
            password.length()
        );

        return (result == 0);
    }

    [[nodiscard]] inline HashArray parse_db_hash(std::string_view db_string) {
        // 1. Strict capacity check. 
        // crypto_pwhash_STRBYTES is 128. If the string is 128 chars or longer, 
        // it is physically impossible to fit a '\0' at the end.
        if (db_string.size() >= crypto_pwhash_STRBYTES) {
            throw PasswordHashParseError("Corrupted DB Auth record: Hash exceeds libsodium container limits.");
        }

        // 2. Format check.
        // Argon2id hashes generated by libsodium start with "$argon2id$"
        if (!db_string.starts_with("$argon2")) {
            throw PasswordHashParseError("Corrupted DB Auth record: Hash is not a valid argon2 format.");
        }

        // 3. Value-initialize the stack buffer to all zeros (0x00)
        HashArray safe_buffer{}; 

        // 4. Copy the string payload in.
        // Because the entire buffer was pre-filled with '\0', the byte sitting 
        // immediately after our copied characters is guaranteed to be a valid terminator.
        std::ranges::copy(db_string, safe_buffer.begin());

        return safe_buffer;
    }

}