name: SonarCloud Analysis
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Better for SonarCloud accuracy
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libjson-c-dev unixodbc-dev libssl-dev

      - name: Install Build Wrapper
        uses: sonarsource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Run Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir bw-output make release

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.cfamily.compile-commands=bw-output/compile_commands.json